version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: clipboard
    versions:
    - 2.0.7
  - dependency-name: marked
    versions:
    - 1.2.8
    - 2.0.0
    - 2.0.1
  - dependency-name: "@primer/octicons"
    versions:
    - 11.2.0
    - 12.0.0
    - 12.1.0
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  registries:
  - npm-registry-registry-npmjs-org
